repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - '--profile=black'
  - repo: 'https://github.com/psf/black'
    rev: 24.4.2
    hooks:
      - id: black
  - repo: 'https://github.com/PyCQA/autoflake'
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - '--remove-all-unused-imports'
          - '--remove-duplicate-keys'
          - '--remove-unused-variables'
          - '--in-place'
